"""
module_grapher.py
=================
Data visualization and animation module for coordinate data.

Provides functions to plot original coordinates, pelvis-relative coordinates,
temporal evolution, 3D trajectories, and animated motion sequences from
the JSON coordinate files generated by the pose estimation pipeline.

Supports 4 keypoints: Pelvis, Right Shoulder, Right Elbow, Right Wrist.
Backward-compatible with older 3-keypoint JSONs (without shoulder data).

Author: Cesar Emilio Castaño Marin
"""

import json
import os
import re
import argparse
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import cm
import matplotlib.animation as animation
import seaborn as sns
from typing import Tuple, Optional
from collections import Counter
from sklearn.metrics import confusion_matrix, accuracy_score

import config


# ===========================
#  MODULE 1: Load Data
# ===========================
def load_coordinates(file_path: str) -> dict:
    """Load coordinates and timestamps from JSON file.

    Returns a dict with keys: pelvis, shoulder, shoulder_ref, wrist, wrist_ref,
    elbow, elbow_ref, timestamps. Shoulder fields may be None if not present
    in the JSON (backward compatibility with 3-keypoint data).

    Raises
    ------
    FileNotFoundError
        If the file does not exist.
    json.JSONDecodeError
        If the file contains invalid JSON.
    KeyError
        If required coordinate fields are missing from the JSON.
    """
    if not os.path.isfile(file_path):
        raise FileNotFoundError(f"File not found: {file_path}")

    with open(file_path, "r") as file:
        data = json.load(file)

    required_keys = [config.FIELD_PELVIS, config.FIELD_WRIST_ORIGINAL,
                     config.FIELD_WRIST_RELATIVE, config.FIELD_ELBOW_ORIGINAL,
                     config.FIELD_ELBOW_RELATIVE, "timestamps"]
    for key in required_keys:
        if key not in data:
            raise KeyError(f"Missing required key '{key}' in {file_path}")

    result = {
        "pelvis": np.array(data[config.FIELD_PELVIS]),
        "wrist": np.array(data[config.FIELD_WRIST_ORIGINAL]),
        "wrist_ref": np.array(data[config.FIELD_WRIST_RELATIVE]),
        "elbow": np.array(data[config.FIELD_ELBOW_ORIGINAL]),
        "elbow_ref": np.array(data[config.FIELD_ELBOW_RELATIVE]),
        "timestamps": np.array(data["timestamps"]),
        "shoulder": None,
        "shoulder_ref": None,
    }

    if config.FIELD_SHOULDER_ORIGINAL in data and len(data[config.FIELD_SHOULDER_ORIGINAL]) > 0:
        result["shoulder"] = np.array(data[config.FIELD_SHOULDER_ORIGINAL])
        result["shoulder_ref"] = np.array(data[config.FIELD_SHOULDER_RELATIVE])

    return result

# ===========================
#  MODULE 2: Plot Functions
# ===========================

def plot_original_coordinates(pelvis: np.ndarray, wrist: np.ndarray, elbow: np.ndarray,
                              shoulder: Optional[np.ndarray] = None) -> None:
    """Plot original (absolute) coordinates of all keypoints."""
    num_points = len(pelvis)

    colors_pelvis = cm.Blues(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))
    colors_wrist = cm.Reds(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))
    colors_elbow = cm.Purples(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))
    colors_shoulder = cm.Greens(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))

    has_shoulder = shoulder is not None
    n_cols = 3 if has_shoulder else 2
    fig, axs = plt.subplots(1, n_cols, figsize=(6 * n_cols, 6))

    # ========== SUBPLOT A: Pelvis + Wrist ==========
    axs[0].set_title("Original Coordinates: Pelvis & Wrist")
    for i in range(num_points - 1):
        axs[0].plot([pelvis[i, 0], pelvis[i+1, 0]],
                    [pelvis[i, 1], pelvis[i+1, 1]], color=colors_pelvis[i])
        axs[0].plot([wrist[i, 0], wrist[i+1, 0]],
                    [wrist[i, 1], wrist[i+1, 1]], color=colors_wrist[i])

    axs[0].scatter(pelvis[:, 0], pelvis[:, 1], c=colors_pelvis, s=20, label="Pelvis")
    axs[0].scatter(wrist[:, 0], wrist[:, 1], c=colors_wrist, s=20, label="Wrist")
    axs[0].set_aspect("equal")
    axs[0].legend()
    axs[0].set_xlabel("Distance (px)")
    axs[0].set_ylabel("Distance (px)")

    # ========== SUBPLOT B: Pelvis + Elbow ==========
    axs[1].set_title("Original Coordinates: Pelvis & Elbow")
    for i in range(num_points - 1):
        axs[1].plot([pelvis[i, 0], pelvis[i+1, 0]],
                    [pelvis[i, 1], pelvis[i+1, 1]], color=colors_pelvis[i])
        axs[1].plot([elbow[i, 0], elbow[i+1, 0]],
                    [elbow[i, 1], elbow[i+1, 1]], color=colors_elbow[i])

    axs[1].scatter(pelvis[:, 0], pelvis[:, 1], c=colors_pelvis, s=20, label="Pelvis")
    axs[1].scatter(elbow[:, 0], elbow[:, 1], c=colors_elbow, s=20, label="Elbow")
    axs[1].set_aspect("equal")
    axs[1].legend()
    axs[1].set_xlabel("Distance (px)")
    axs[1].set_ylabel("Distance (px)")

    # ========== SUBPLOT C: Pelvis + Shoulder (if available) ==========
    if has_shoulder:
        axs[2].set_title("Original Coordinates: Pelvis & Shoulder")
        for i in range(num_points - 1):
            axs[2].plot([pelvis[i, 0], pelvis[i+1, 0]],
                        [pelvis[i, 1], pelvis[i+1, 1]], color=colors_pelvis[i])
            axs[2].plot([shoulder[i, 0], shoulder[i+1, 0]],
                        [shoulder[i, 1], shoulder[i+1, 1]], color=colors_shoulder[i])

        axs[2].scatter(pelvis[:, 0], pelvis[:, 1], c=colors_pelvis, s=20, label="Pelvis")
        axs[2].scatter(shoulder[:, 0], shoulder[:, 1], c=colors_shoulder, s=20, label="Shoulder")
        axs[2].set_aspect("equal")
        axs[2].legend()
        axs[2].set_xlabel("Distance (px)")
        axs[2].set_ylabel("Distance (px)")

    fig.text(
        0.5, 0.02,
        "Lighter colors represent the beginning of the movement, while darker colors indicate its end.",
        ha="center", fontsize=9, style="italic"
    )

    plt.tight_layout(rect=[0, 0.05, 1, 1])
    plt.show()

def plot_relative_coordinates(wrist_ref: np.ndarray, elbow_ref: np.ndarray,
                              shoulder_ref: Optional[np.ndarray] = None) -> None:
    """Plot pelvis-relative coordinates of wrist, elbow, and optionally shoulder."""
    num_points = len(wrist_ref)

    colors_wrist = cm.Greens(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))
    colors_elbow = cm.Oranges(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))
    colors_shoulder = cm.Blues(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))

    has_shoulder = shoulder_ref is not None
    n_cols = 3 if has_shoulder else 2
    fig, axs = plt.subplots(1, n_cols, figsize=(6 * n_cols, 6))

    # ========== SUBPLOT A: Wrist relative ==========
    axs[0].set_title("Relative Coordinates: Wrist - Pelvis")
    for i in range(num_points - 1):
        axs[0].plot([wrist_ref[i, 0], wrist_ref[i+1, 0]],
                    [wrist_ref[i, 1], wrist_ref[i+1, 1]], color=colors_wrist[i])
    axs[0].scatter(wrist_ref[:, 0], wrist_ref[:, 1], c=colors_wrist, s=20)
    axs[0].set_aspect("equal")
    axs[0].set_xlabel("Distance (px)")
    axs[0].set_ylabel("Distance (px)")

    # ========== SUBPLOT B: Elbow relative ==========
    axs[1].set_title("Relative Coordinates: Elbow - Pelvis")
    for i in range(num_points - 1):
        axs[1].plot([elbow_ref[i, 0], elbow_ref[i+1, 0]],
                    [elbow_ref[i, 1], elbow_ref[i+1, 1]], color=colors_elbow[i])
    axs[1].scatter(elbow_ref[:, 0], elbow_ref[:, 1], c=colors_elbow, s=20)
    axs[1].set_aspect("equal")
    axs[1].set_xlabel("Distance (px)")
    axs[1].set_ylabel("Distance (px)")

    # ========== SUBPLOT C: Shoulder relative (if available) ==========
    if has_shoulder:
        axs[2].set_title("Relative Coordinates: Shoulder - Pelvis")
        for i in range(num_points - 1):
            axs[2].plot([shoulder_ref[i, 0], shoulder_ref[i+1, 0]],
                        [shoulder_ref[i, 1], shoulder_ref[i+1, 1]], color=colors_shoulder[i])
        axs[2].scatter(shoulder_ref[:, 0], shoulder_ref[:, 1], c=colors_shoulder, s=20)
        axs[2].set_aspect("equal")
        axs[2].set_xlabel("Distance (px)")
        axs[2].set_ylabel("Distance (px)")

    fig.text(
        0.5, 0.02,
        "Lighter colors represent the beginning of the movement, while darker colors indicate its end.",
        ha="center", fontsize=9, style="italic"
    )

    plt.tight_layout(rect=[0, 0.05, 1, 1])
    plt.show()

def plot_temporal(wrist_ref: np.ndarray, elbow_ref: np.ndarray, timestamps: np.ndarray,
                  shoulder_ref: Optional[np.ndarray] = None) -> None:
    """Plot time progression for wrist, elbow, and optionally shoulder (X & Y)."""

    has_shoulder = shoulder_ref is not None
    n_rows = 3 if has_shoulder else 2
    fig, axs = plt.subplots(n_rows, 2, figsize=(12, 5 * n_rows), sharex=True)

    # ------------------------
    # Row 0: Wrist X / Y
    # ------------------------
    axs[0, 0].set_title("Wrist X over Time")
    axs[0, 0].plot(timestamps, wrist_ref[:, 0], color="green")
    axs[0, 0].grid(True)
    axs[0, 0].set_xlabel("Time (seconds)")
    axs[0, 0].set_ylabel("Distance to Reference (px)")

    axs[0, 1].set_title("Wrist Y over Time")
    axs[0, 1].plot(timestamps, wrist_ref[:, 1], color="darkgreen")
    axs[0, 1].grid(True)
    axs[0, 1].set_xlabel("Time (seconds)")
    axs[0, 1].set_ylabel("Distance to Reference (px)")

    # ------------------------
    # Row 1: Elbow X / Y
    # ------------------------
    axs[1, 0].set_title("Elbow X over Time")
    axs[1, 0].plot(timestamps, elbow_ref[:, 0], color="orange")
    axs[1, 0].grid(True)
    axs[1, 0].set_xlabel("Time (seconds)")
    axs[1, 0].set_ylabel("Distance to Reference (px)")

    axs[1, 1].set_title("Elbow Y over Time")
    axs[1, 1].plot(timestamps, elbow_ref[:, 1], color="red")
    axs[1, 1].grid(True)
    axs[1, 1].set_xlabel("Time (seconds)")
    axs[1, 1].set_ylabel("Distance to Reference (px)")

    # ------------------------
    # Row 2: Shoulder X / Y (if available)
    # ------------------------
    if has_shoulder:
        axs[2, 0].set_title("Shoulder X over Time")
        axs[2, 0].plot(timestamps, shoulder_ref[:, 0], color="blue")
        axs[2, 0].grid(True)
        axs[2, 0].set_xlabel("Time (seconds)")
        axs[2, 0].set_ylabel("Distance to Reference (px)")

        axs[2, 1].set_title("Shoulder Y over Time")
        axs[2, 1].plot(timestamps, shoulder_ref[:, 1], color="darkblue")
        axs[2, 1].grid(True)
        axs[2, 1].set_xlabel("Time (seconds)")
        axs[2, 1].set_ylabel("Distance to Reference (px)")

    plt.tight_layout()
    plt.show()

def plot_3d(wrist_ref: np.ndarray, elbow_ref: np.ndarray, timestamps: np.ndarray,
            shoulder_ref: Optional[np.ndarray] = None) -> None:
    """3D trajectory of wrist, elbow, and optionally shoulder (X, Y, Time)."""

    has_shoulder = shoulder_ref is not None
    n_cols = 3 if has_shoulder else 2
    fig = plt.figure(figsize=(7 * n_cols, 6))

    # ===== Wrist =====
    ax1 = fig.add_subplot(1, n_cols, 1, projection="3d")
    ax1.plot3D(wrist_ref[:, 0], timestamps, wrist_ref[:, 1], color="green")
    ax1.set_title("3D Wrist Trajectory (X, Y, Time)")
    ax1.set_xlabel("Distance in X to Reference (px)")
    ax1.set_ylabel("Time")
    ax1.set_zlabel("Distance in Y to Reference (px)")

    # ===== Elbow =====
    ax2 = fig.add_subplot(1, n_cols, 2, projection="3d")
    ax2.plot3D(elbow_ref[:, 0], timestamps, elbow_ref[:, 1], color="purple")
    ax2.set_title("3D Elbow Trajectory (X, Y, Time)")
    ax2.set_xlabel("Distance in X to Reference (px)")
    ax2.set_ylabel("Time")
    ax2.set_zlabel("Distance in Y to Reference (px)")

    # ===== Shoulder =====
    if has_shoulder:
        ax3 = fig.add_subplot(1, n_cols, 3, projection="3d")
        ax3.plot3D(shoulder_ref[:, 0], timestamps, shoulder_ref[:, 1], color="blue")
        ax3.set_title("3D Shoulder Trajectory (X, Y, Time)")
        ax3.set_xlabel("Distance in X to Reference (px)")
        ax3.set_ylabel("Time")
        ax3.set_zlabel("Distance in Y to Reference (px)")

    plt.tight_layout()
    plt.show()

# ===========================
#  MODULE 3: Parser Wrapper
# ===========================
def plot_coordinates(args: argparse.Namespace) -> None:
    """Main function that receives parser arguments and calls the appropriate plot."""
    coords = load_coordinates(args.file)

    pelvis = coords["pelvis"]
    wrist = coords["wrist"]
    wrist_ref = coords["wrist_ref"]
    elbow = coords["elbow"]
    elbow_ref = coords["elbow_ref"]
    timestamps = coords["timestamps"]
    shoulder = coords["shoulder"]
    shoulder_ref = coords["shoulder_ref"]

    print(f"\n[INFO] File loaded: {args.file}")
    print(f"[INFO] Plot type selected: {args.type}")
    if shoulder is not None:
        print("[INFO] Shoulder data found (4-keypoint format)\n")
    else:
        print("[INFO] No shoulder data (3-keypoint format)\n")

    if args.type == "original":
        plot_original_coordinates(pelvis, wrist, elbow, shoulder)

    elif args.type == "relative":
        plot_relative_coordinates(wrist_ref, elbow_ref, shoulder_ref)

    elif args.type == "temporal":
        plot_temporal(wrist_ref, elbow_ref, timestamps, shoulder_ref)

    elif args.type == "3d":
        plot_3d(wrist_ref, elbow_ref, timestamps, shoulder_ref)

    elif args.type == "all":
        plot_original_coordinates(pelvis, wrist, elbow, shoulder)
        plot_relative_coordinates(wrist_ref, elbow_ref, shoulder_ref)
        plot_temporal(wrist_ref, elbow_ref, timestamps, shoulder_ref)
        plot_3d(wrist_ref, elbow_ref, timestamps, shoulder_ref)

# ===========================
#  MODULE 4: Motion Animation
# ===========================
def animate_motion(args: argparse.Namespace) -> None:
    """
    Animates Pelvis, Left Shoulder, Right Elbow, and Right Wrist (original coordinates)
    with automatic zoom, normal Y-axis, and start markers for each joint.
    Connects joints as a kinematic chain: Pelvis -> Shoulder -> Elbow -> Wrist.
    """
    json_path = args.file
    print(f"\n[INFO] Generating animation from: {json_path}\n")

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    pelvis = np.array(data[config.FIELD_PELVIS])
    elbow = np.array(data[config.FIELD_ELBOW_ORIGINAL])
    wrist = np.array(data[config.FIELD_WRIST_ORIGINAL])
    timestamps = np.array(data["timestamps"])
    metadata = data.get("metadata", {})
    fps = metadata.get("fps", 30)

    has_shoulder = config.FIELD_SHOULDER_ORIGINAL in data and len(data[config.FIELD_SHOULDER_ORIGINAL]) > 0
    if has_shoulder:
        shoulder = np.array(data[config.FIELD_SHOULDER_ORIGINAL])

    # --- Playback speed (slower for clarity) ---
    playback_speed = config.ANIMATION_PLAYBACK_SPEED
    interval = (1000 / fps) / playback_speed

    # --- Compute coordinate bounds for zoom ---
    points_list = [pelvis, elbow, wrist]
    if has_shoulder:
        points_list.append(shoulder)
    all_points = np.vstack(points_list)
    x_min, x_max = np.min(all_points[:, 0]), np.max(all_points[:, 0])
    y_min, y_max = np.min(all_points[:, 1]), np.max(all_points[:, 1])
    margin_x = (x_max - x_min) * config.COORDINATE_MARGIN_RATIO
    margin_y = (y_max - y_min) * config.COORDINATE_MARGIN_RATIO

    # --- Setup figure ---
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_title(f"Motion Animation (Original) - Frontal View of the Player\n{metadata.get('video_name', '')}")
    ax.set_xlim(x_min - margin_x, x_max + margin_x)
    ax.set_ylim(y_min - margin_y, y_max + margin_y)
    ax.set_xlabel("Distance (px)")
    ax.set_ylabel("Distance (px)")
    ax.grid(True, linestyle="--", alpha=0.5)

    # --- Define graphical elements ---
    scat_pelvis, = ax.plot([], [], 'o', color='blue', label="Pelvis", markersize=8)
    scat_elbow, = ax.plot([], [], 'o', color='green', label="Right Elbow", markersize=8)
    scat_wrist, = ax.plot([], [], 'o', color='red', label="Right Wrist", markersize=8)

    # Kinematic chain line: pelvis -> (shoulder) -> elbow -> wrist
    line_arm, = ax.plot([], [], '-', color='orange', lw=2, label="Arm")

    # Trails
    trail_pelvis, = ax.plot([], [], '--', color='blue', alpha=0.4)
    trail_elbow, = ax.plot([], [], '--', color='green', alpha=0.4)
    trail_wrist, = ax.plot([], [], '--', color='red', alpha=0.4)

    # Start markers (hollow circles)
    start_pelvis, = ax.plot([], [], 'o', color='blue', markersize=10, fillstyle='none', label="Start Pelvis")
    start_elbow, = ax.plot([], [], 'o', color='green', markersize=10, fillstyle='none', label="Start Elbow")
    start_wrist, = ax.plot([], [], 'o', color='red', markersize=10, fillstyle='none', label="Start Wrist")

    # Shoulder-specific elements (only if data exists)
    all_elements = [scat_pelvis, scat_elbow, scat_wrist, line_arm,
                    trail_pelvis, trail_elbow, trail_wrist,
                    start_pelvis, start_elbow, start_wrist]

    if has_shoulder:
        scat_shoulder, = ax.plot([], [], 'o', color='purple', label="Left Shoulder", markersize=8)
        trail_shoulder, = ax.plot([], [], '--', color='purple', alpha=0.4)
        start_shoulder, = ax.plot([], [], 'o', color='purple', markersize=10, fillstyle='none', label="Start Shoulder")
        all_elements.extend([scat_shoulder, trail_shoulder, start_shoulder])

    ax.legend(loc='upper left', fontsize=7)

    # --- Initialization ---
    def init():
        for element in all_elements:
            element.set_data([], [])
        return tuple(all_elements)

    # --- Update function ---
    def update(i):
        px, py = pelvis[i]
        ex, ey = elbow[i]
        wx, wy = wrist[i]

        scat_pelvis.set_data(px, py)
        scat_elbow.set_data(ex, ey)
        scat_wrist.set_data(wx, wy)

        if has_shoulder:
            sx, sy = shoulder[i]
            scat_shoulder.set_data(sx, sy)
            # Kinematic chain: Pelvis -> Shoulder -> Elbow -> Wrist
            line_arm.set_data([px, sx, ex, wx], [py, sy, ey, wy])
            trail_shoulder.set_data(shoulder[:i, 0], shoulder[:i, 1])
            start_shoulder.set_data(shoulder[0, 0], shoulder[0, 1])
        else:
            # Without shoulder: Elbow -> Wrist only
            line_arm.set_data([ex, wx], [ey, wy])

        # Trails (motion history)
        trail_pelvis.set_data(pelvis[:i, 0], pelvis[:i, 1])
        trail_elbow.set_data(elbow[:i, 0], elbow[:i, 1])
        trail_wrist.set_data(wrist[:i, 0], wrist[:i, 1])

        # Start positions (fixed)
        start_pelvis.set_data(pelvis[0, 0], pelvis[0, 1])
        start_elbow.set_data(elbow[0, 0], elbow[0, 1])
        start_wrist.set_data(wrist[0, 0], wrist[0, 1])

        return tuple(all_elements)

    # --- Create animation ---
    ani = animation.FuncAnimation(
        fig, update, frames=len(timestamps),
        init_func=init, blit=True, interval=interval, repeat=False
    )

    plt.tight_layout()
    plt.show()


# ============================================================
#  THESIS ARTIFACT GENERATION
# ============================================================
# Private helpers for publication-ready figures.

def _plot_learning_curves(history: dict, display_name: str, out_path: str):
    """Plot and save learning curves (loss + accuracy) from training history."""
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 6))

    ax1.plot(history['loss'],     label='Training Loss')
    ax1.plot(history['val_loss'], label='Validation Loss')
    ax1.set_title(f'Learning Curves \u2014 {display_name}')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Loss')
    ax1.legend()
    ax1.grid(True)

    ax2.plot(history['accuracy'],     label='Training Accuracy')
    ax2.plot(history['val_accuracy'], label='Validation Accuracy')
    ax2.set_title(f'Learning Curves \u2014 {display_name}')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Accuracy')
    ax2.legend()
    ax2.grid(True)

    plt.tight_layout()
    plt.savefig(out_path, dpi=config.PLOT_DPI)
    plt.close()


def _plot_confusion_matrix(y_true, y_pred, display_name: str,
                           class_labels, out_path: str):
    """Plot and save a confusion matrix heatmap."""
    valid = sorted(set(list(y_true) + list(y_pred)))
    names = [class_labels[c] if c < len(class_labels) else str(c) for c in valid]
    cm_data = confusion_matrix(y_true, y_pred, labels=valid)

    plt.figure(figsize=(8, 6))
    sns.heatmap(cm_data, annot=True, fmt='d', cmap='Blues',
                xticklabels=names, yticklabels=names)
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title(f'Confusion Matrix \u2014 {display_name}')
    plt.tight_layout()
    plt.savefig(out_path, dpi=config.PLOT_DPI)
    plt.close()


def _plot_class_dist_thesis(y_true, y_pred, display_name: str,
                            class_labels, out_path: str):
    """Plot and save true vs predicted class distribution bar chart."""
    true_c = Counter(y_true)
    pred_c = Counter(y_pred)
    classes = sorted(set(list(true_c) + list(pred_c)))
    names = [class_labels[c] if c < len(class_labels) else str(c) for c in classes]

    plt.figure(figsize=(10, 6))
    x = np.arange(len(classes))
    plt.bar(x - 0.2, [true_c.get(c, 0) for c in classes], width=0.4, label='True')
    plt.bar(x + 0.2, [pred_c.get(c, 0) for c in classes], width=0.4, label='Predicted')
    plt.xticks(x, names, rotation=15)
    plt.title(f'True vs Predicted Class Distribution \u2014 {display_name}')
    plt.xlabel('Class')
    plt.ylabel('Clips')
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_path, dpi=config.PLOT_DPI)
    plt.close()


# -----------------------------------------------------------
# CLI-callable thesis functions
# -----------------------------------------------------------

def regen_plots(args: argparse.Namespace) -> None:
    """Regenerate all 15 experiment plots with English labels and display names.

    Reads learning curves from saved training_history.json and regenerates
    confusion matrix + class distribution by running inference on the test set
    reconstructed from the same random_state=42 split.

    Output: PNG files copied to the thesis Images/Experimentation/ directory.
    """
    from tf_keras.models import load_model as tf_load_model
    from Modules.module_data import load_all_jsons, build_test_set

    matplotlib.use('Agg')

    thesis_exp_dir = os.path.join(config.get_thesis_dir(args), 'Images', 'Experimentation')
    coords_dir = args.directory

    print(f"[INFO] Loading sequences from {coords_dir} ...")
    seqs, labels = load_all_jsons(coords_dir)
    print(f"[INFO] Loaded {len(seqs)} sequences")

    status = {}

    for exp in config.EXPERIMENTS:
        key          = exp['key']
        display_name = exp['display_name']
        results_dir  = os.path.join(config.RESULTS_DIR, exp['results_folder'])
        thesis_subdir = os.path.join(thesis_exp_dir, exp['thesis_subdir'])
        os.makedirs(thesis_subdir, exist_ok=True)

        exp_status = {'learning_curves': False, 'confusion_matrix': False,
                      'class_distribution': False}
        print(f"\n  [{key}] {display_name}")

        # ---- Learning curves ----
        hist_path = os.path.join(results_dir, 'training_history.json')
        if os.path.exists(hist_path):
            with open(hist_path) as f:
                history = json.load(f)
            _plot_learning_curves(
                history, display_name,
                os.path.join(thesis_subdir, 'learning_curves.png'))
            exp_status['learning_curves'] = True
            print(f"    [OK] learning_curves.png")
        else:
            print(f"    [SKIP] training_history.json not found")

        # ---- Confusion matrix + class distribution ----
        model_path = exp['model_path']
        if not os.path.exists(model_path):
            print(f"    [SKIP] model not found at {model_path}")
            status[key] = exp_status
            continue

        try:
            model      = tf_load_model(config.safe_model_path(model_path))
            n_features = model.input_shape[-1]
            n_out      = model.output_shape[-1]
            print(f"    [INFO] model loaded (inputs={n_features}, outputs={n_out})")

            X_test, y_test = build_test_set(seqs, labels, n_features)
            if X_test is None:
                print(f"    [SKIP] no matching test sequences for {n_features} features")
                status[key] = exp_status
                continue

            y_pred = np.argmax(model.predict(X_test, verbose=0), axis=1)
            if n_out != 5:
                y_pred = np.array([min(p // 2, 4) for p in y_pred])

            _plot_confusion_matrix(
                y_test, y_pred, display_name, config.CLASS_LABELS,
                os.path.join(thesis_subdir, 'confusion_matrix.png'))
            _plot_class_dist_thesis(
                y_test, y_pred, display_name, config.CLASS_LABELS,
                os.path.join(thesis_subdir, 'class_distribution.png'))

            exp_status['confusion_matrix']   = True
            exp_status['class_distribution'] = True
            print(f"    [OK] confusion_matrix.png + class_distribution.png "
                  f"(acc={accuracy_score(y_test, y_pred):.3f})")

        except Exception as err:
            print(f"    [ERROR] {err}")

        status[key] = exp_status

    # Summary
    print("\n[SUMMARY] Task regenPlots:")
    for key, s in status.items():
        parts = ' '.join(f"{k}={'OK' if v else 'FAIL'}" for k, v in s.items())
        print(f"  {key}: {parts}")


def label_dist(args: argparse.Namespace) -> None:
    """Generate dataset-wide class distribution histogram.

    Output: PNG saved to the thesis Images/Experimentation/ directory.
    """
    from Modules.module_data import load_all_jsons

    matplotlib.use('Agg')

    coords_dir = args.directory
    print(f"[INFO] Loading sequences from {coords_dir} ...")
    _, labels = load_all_jsons(coords_dir)
    print(f"[INFO] Loaded {len(labels)} labels")

    classes = [config.grade_to_class(g) for g in labels]
    counts  = [Counter(classes).get(c, 0) for c in range(5)]
    colors  = ['#2196F3', '#4CAF50', '#FF9800', '#F44336', '#9C27B0']

    plt.figure(figsize=(10, 6))
    bars = plt.bar(range(5), counts, color=colors)
    for bar, cnt in zip(bars, counts):
        plt.text(bar.get_x() + bar.get_width() / 2.0, bar.get_height() + 2,
                 str(cnt), ha='center', va='bottom', fontsize=11)
    plt.xticks(range(5), config.CLASS_LABELS)
    plt.xlabel('Quality Class')
    plt.ylabel('Number of Clips')
    plt.title(f'Class Distribution \u2014 Full Dataset ({len(labels)} clips)')
    plt.tight_layout()

    out_dir = os.path.join(config.get_thesis_dir(args), 'Images', 'Experimentation')
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, 'label_distribution.png')
    plt.savefig(out_path, dpi=config.PLOT_DPI)
    plt.close()

    print(f"[OK] label_distribution.png -> {out_path}")
    for c, cnt in zip(config.CLASS_LABELS, counts):
        print(f"  {c}: {cnt}")


def sys_output(args: argparse.Namespace) -> None:
    """Generate side-by-side low vs high quality joint trajectory figure.

    Scans all clips in *args.directory*, finds the first correctly classified
    Very Low/Low clip and first correctly classified Excellent clip using
    the BiLSTM Final Model (LSTM_Test03), and plots wrist and elbow Y
    trajectories side by side.

    Output: system_output_example.png saved to thesis Images/Methodology/.
    """
    from tf_keras.models import load_model as tf_load_model
    from tf_keras.utils import pad_sequences as kpad
    from Modules.module_data import normalize_sequence

    matplotlib.use('Agg')

    lstm_exp = next(e for e in config.EXPERIMENTS if e['key'] == 'LSTM_Test03')
    model_path = lstm_exp['model_path']
    if not os.path.exists(model_path):
        print(f"[SKIP] LSTM_Test03 model not found at {model_path}")
        return

    model = tf_load_model(config.safe_model_path(model_path))
    coords_dir = args.directory

    low_clip  = None   # class 0 or 1
    high_clip = None   # class 4

    for root, _, files in os.walk(coords_dir):
        for fname in files:
            if not fname.endswith('.json'):
                continue
            if low_clip and high_clip:
                break

            with open(os.path.join(root, fname)) as f:
                data = json.load(f)

            grade = int(data.get('metadata', {}).get('grade', 0) or 0)
            if grade == 0:
                continue

            true_class = config.grade_to_class(grade)
            if true_class not in [0, 1, 4]:
                continue
            if true_class in [0, 1] and low_clip:
                continue
            if true_class == 4 and high_clip:
                continue

            pelvis   = np.array(data.get(config.FIELD_PELVIS, []))
            shoulder = np.array(data.get(config.FIELD_SHOULDER_RELATIVE, []))
            elbow    = np.array(data.get(config.FIELD_ELBOW_RELATIVE, []))
            hand     = np.array(data.get(config.FIELD_WRIST_RELATIVE, []))

            if not (len(pelvis) and len(elbow) and len(hand)):
                continue

            if len(shoulder) > 0:
                L   = min(len(pelvis), len(shoulder), len(elbow), len(hand))
                seq = np.concatenate([pelvis[:L], shoulder[:L], elbow[:L], hand[:L]], axis=1)
            else:
                L   = min(len(pelvis), len(elbow), len(hand))
                seq = np.concatenate([pelvis[:L], elbow[:L], hand[:L]], axis=1)

            if L < 10 or seq.shape[1] != 8:
                continue

            norm_seq = normalize_sequence(seq)
            padded   = kpad([norm_seq], maxlen=config.MAX_SEQUENCE_LENGTH,
                            dtype='float32', padding='post', truncating='post')
            pred_class = int(np.argmax(model.predict(padded, verbose=0), axis=1)[0])

            if pred_class == true_class:
                clip = (seq, true_class, pred_class, fname)
                if true_class in [0, 1]:
                    low_clip  = clip
                else:
                    high_clip = clip

    if not low_clip or not high_clip:
        print(f"[WARN] Could not find both clip types "
              f"(low={'found' if low_clip else 'not found'}, "
              f"high={'found' if high_clip else 'not found'})")
        return

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    def _panel(ax, seq, pred_class, fname):
        n = min(len(seq), 90)
        ax.plot(np.arange(n), seq[:n, 7], label='Right Wrist Y',  linewidth=2)
        ax.plot(np.arange(n), seq[:n, 5], label='Right Elbow Y',  linewidth=2, linestyle='--')
        ax.set_xlabel('Frame')
        ax.set_ylabel('Relative Y Coordinate (px)')
        ax.legend()
        ax.grid(True, alpha=0.3)
        ax.text(0.05, 0.95,
                f'Predicted: {config.CLASS_LABELS[pred_class]}',
                transform=ax.transAxes, fontsize=12, verticalalignment='top',
                bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.8))

    low_seq, low_true, low_pred, low_file   = low_clip
    high_seq, high_true, high_pred, high_file = high_clip

    ax1.set_title(f'{config.CLASS_LABELS[low_true]} Quality Execution\n({low_file})')
    _panel(ax1, low_seq, low_pred, low_file)

    ax2.set_title(f'{config.CLASS_LABELS[high_true]} Quality Execution\n({high_file})')
    _panel(ax2, high_seq, high_pred, high_file)

    plt.suptitle('System Output Comparison \u2014 BiLSTM Final Model', fontsize=14)
    plt.tight_layout()

    out_dir = os.path.join(config.get_thesis_dir(args), 'Images', 'Methodology')
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, 'system_output_example.png')
    plt.savefig(out_path, dpi=config.PLOT_DPI)
    plt.close()
    print(f"[OK] system_output_example.png -> {out_path}")


# ============================================================
#  THESIS VISUALIZATION — DATASET MOSAIC & TRAJECTORY PLOTS
# ============================================================
# Per-class badge colors (consistent across all thesis figures).
_CLASS_COLORS = {
    0: '#d62728',  # Very Low  — red
    1: '#ff7f0e',  # Low       — orange
    2: '#2ca02c',  # Medium    — green
    3: '#1f77b4',  # High      — blue
    4: '#9467bd',  # Excellent — purple
}


def _parse_clip_meta(filename: str):
    """Return (player_id, part, clip_num, grade) parsed from a filename, or None."""
    m = re.search(config.FILENAME_REGEX, filename)
    if m:
        return int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4))
    return None


def _find_representative_clips(coords_dir: str, clips_dir: str) -> list:
    """Find one JSON+video pair per quality class (0–4).

    Prefers clips that also have a matching .mp4 in clips_dir.
    Preferred player per class: 10 for VeryLow/Medium/Excellent, 3 for Low/High.

    Returns a list of 5 dicts (one per class, in order) or None if a class has
    no candidates. Each dict has keys: label, color, grade, player_id,
    clip_name, json_path, video_path (str or None).
    """
    preferred_player = {0: 10, 1: 3, 2: 10, 3: 3, 4: 10}
    buckets = {c: [] for c in range(5)}

    for root, _, files in os.walk(coords_dir):
        for fname in sorted(files):
            if not fname.endswith('.json'):
                continue
            meta = _parse_clip_meta(fname)
            if meta is None:
                continue
            player_id, _, _, grade = meta
            cls = config.grade_to_class(grade)
            rel = os.path.relpath(os.path.join(root, fname), coords_dir)
            vid = os.path.join(clips_dir, rel.replace('.json', '.mp4'))
            buckets[cls].append({
                'label':      config.CLASS_LABELS[cls],
                'color':      _CLASS_COLORS[cls],
                'grade':      grade,
                'player_id':  player_id,
                'clip_name':  os.path.splitext(fname)[0],
                'json_path':  os.path.join(root, fname),
                'video_path': vid if os.path.exists(vid) else None,
            })

    result = []
    for cls in range(5):
        cands = buckets[cls]
        if not cands:
            result.append(None)
            continue
        pid = preferred_player[cls]
        pick = (next((c for c in cands if c['player_id'] == pid and c['video_path']), None)
                or next((c for c in cands if c['video_path']), None)
                or cands[0])
        result.append(pick)
    return result


def _extract_video_frame(video_path: str, pct: float = 0.40) -> np.ndarray:
    """Extract the frame at *pct* of clip duration. Returns an RGB uint8 ndarray."""
    try:
        import cv2
    except ImportError:
        raise ImportError("OpenCV (cv2) required. Install with: pip install opencv-python")
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Cannot open video: {video_path}")
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.set(cv2.CAP_PROP_POS_FRAMES, max(0, int(total * pct) - 1))
    ret, frame = cap.read()
    cap.release()
    if not ret:
        raise RuntimeError(f"Cannot read frame from {video_path}")
    return cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)


def _save_temporal_plot(coords: dict, title: str, clip_name: str, out_path: str) -> None:
    """Save a temporal X/Y-over-frame plot for wrist, elbow, and shoulder.

    Wrist, elbow, and shoulder values are displacements relative to the pelvis
    reference point (pelvis is the origin, so 0 = same position as pelvis).
    Pelvis coordinates are absolute pixel positions in the image frame.
    """
    wrist_ref    = coords['wrist_ref']
    elbow_ref    = coords['elbow_ref']
    shoulder_ref = coords['shoulder_ref']
    has_shoulder = shoulder_ref is not None

    n      = len(wrist_ref)
    frames = np.arange(n)
    n_rows = 3 if has_shoulder else 2

    fig, axs = plt.subplots(n_rows, 2, figsize=(13, 4 * n_rows))
    fig.patch.set_facecolor('white')
    fig.suptitle(f"{title}\nClip: {clip_name}", fontsize=11, fontweight='bold')

    # Wrist/elbow/shoulder values are displacements relative to the pelvis.
    joint_rows = [
        ('Right Wrist (relative to pelvis)',    wrist_ref,    'green',     'darkgreen'),
        ('Right Elbow (relative to pelvis)',    elbow_ref,    'orange',    'red'),
    ]
    if has_shoulder:
        joint_rows.append(
            ('Left Shoulder (relative to pelvis)', shoulder_ref, 'steelblue', 'darkblue')
        )

    for row, (jname, jdata, cx, cy) in enumerate(joint_rows):
        for col, (axis_label, vals, color) in enumerate([('X', jdata[:, 0], cx),
                                                          ('Y', jdata[:, 1], cy)]):
            ax = axs[row, col]
            ax.plot(frames, vals, color=color, linewidth=1.5)
            ax.set_title(f'{jname}\n{axis_label} component over frame', fontsize=9.5)
            ax.set_xlabel('Frame number', fontsize=9)
            ax.set_ylabel(f'{axis_label} displacement from pelvis (px)', fontsize=9)
            ax.grid(True, alpha=0.3)
            ax.set_facecolor('#fafafa')
            ax.set_xlim(0, n - 1)

    fig.text(0.5, -0.01,
             "Pelvis is the reference origin. Positive values indicate displacement "
             "to the right (X) or downward (Y) from the pelvis position.",
             ha='center', fontsize=8, color='#555555', style='italic')

    plt.tight_layout()
    plt.savefig(out_path, dpi=config.PLOT_DPI, bbox_inches='tight', facecolor='white')
    plt.close()


def _save_3d_plot_file(coords: dict, title: str, clip_name: str, out_path: str) -> None:
    """Save a 3D trajectory plot (X, Y, Frame axis) for wrist, elbow, and shoulder.

    Each joint is plotted in a 3D space where X and Y axes represent the joint's
    displacement from the pelvis reference point, and the depth axis is the frame
    number (i.e., time progression through the clip).
    """
    wrist_ref    = coords['wrist_ref']
    elbow_ref    = coords['elbow_ref']
    shoulder_ref = coords['shoulder_ref']
    has_shoulder = shoulder_ref is not None

    n = len(wrist_ref)
    t = np.arange(n)

    n_cols = 3 if has_shoulder else 2
    fig = plt.figure(figsize=(7 * n_cols, 7))
    fig.patch.set_facecolor('white')
    fig.suptitle(
        f"{title}\nClip: {clip_name}\n"
        "X and Y axes: displacement from pelvis (px)  ·  Depth axis: frame number",
        fontsize=10, fontweight='bold'
    )

    specs = [
        ('Right Wrist (relative to pelvis)',    wrist_ref,    'green'),
        ('Right Elbow (relative to pelvis)',    elbow_ref,    'purple'),
    ]
    if has_shoulder:
        specs.append(('Left Shoulder (relative to pelvis)', shoulder_ref, 'steelblue'))

    for idx, (jname, jdata, color) in enumerate(specs, start=1):
        ax = fig.add_subplot(1, n_cols, idx, projection='3d')
        ax.plot3D(jdata[:, 0], t, jdata[:, 1], color=color, linewidth=1.5)
        ax.set_title(f'3D Trajectory\n{jname}', fontsize=9.5)
        ax.set_xlabel('X from pelvis (px)', fontsize=7.5, labelpad=6)
        ax.set_ylabel('Frame number',       fontsize=7.5, labelpad=6)
        ax.set_zlabel('Y from pelvis (px)', fontsize=7.5, labelpad=6)
        ax.tick_params(labelsize=7)

    plt.tight_layout()
    plt.savefig(out_path, dpi=config.PLOT_DPI, bbox_inches='tight', facecolor='white')
    plt.close()


# -----------------------------------------------------------
# CLI-callable thesis visualization functions
# -----------------------------------------------------------

def dataset_mosaic(args: argparse.Namespace) -> None:
    """Generate an enhanced dataset mosaic for the thesis Dataset section.

    Layout — 5 rows × 2 columns (one row per quality class):
      Column 0: Representative video frame at 40% of clip duration, displayed at
                its natural aspect ratio (no stretching). Carries a color-coded
                quality-class badge, clip filename, player ID, and grade as an
                in-frame annotation.
      Column 1: Trajectory subplot showing right-wrist Y, right-elbow Y, and
                left-shoulder Y over frames. All joint values are displacements
                relative to the pelvis reference point (px).

    Clips are auto-selected from coords_dir: one per class, preferring the
    player configured in _find_representative_clips, and requiring a matching
    .mp4 video file in clips_dir.

    Output: {thesis_dir}/Images/Experimentation/dataset_mosaic.png

    CLI usage:
        python main.py thesisMosaic --clips_dir "../Videos/Clips" \\
               --coords_dir "../Coordinates" [--thesis_dir "..."]
    """
    matplotlib.use('Agg')

    clips_dir  = args.clips_dir
    coords_dir = args.coords_dir
    thesis_dir = config.get_thesis_dir(args)
    out_dir    = os.path.join(thesis_dir, 'Images', 'Experimentation')
    os.makedirs(out_dir, exist_ok=True)

    print(f"[INFO] Scanning coords: {coords_dir}")
    print(f"[INFO] Scanning clips:  {clips_dir}")
    clips = _find_representative_clips(coords_dir, clips_dir)

    print("[INFO] Selected clips for mosaic:")
    for c in clips:
        if c:
            vid = os.path.basename(c['video_path']) if c['video_path'] else 'NO VIDEO'
            print(f"  {c['label']:12s} -> {c['clip_name']}  |  video: {vid}")

    try:
        import cv2 as _cv2
    except ImportError:
        _cv2 = None

    # Probe one frame to determine the natural aspect ratio (width / height).
    frame_ar = 16 / 9
    for c in clips:
        if c and c['video_path'] and _cv2 is not None:
            try:
                probe = _extract_video_frame(c['video_path'], pct=0.40)
                frame_ar = probe.shape[1] / probe.shape[0]
                break
            except Exception:
                pass

    # Figure dimensions: left col holds the frame at natural aspect ratio.
    # With width_ratios=[1,1] and total width W, each col = W/2 inches.
    # Row height is set so that (W/2) / frame_ar = natural frame height.
    total_w  = 18.0          # inches
    col_w    = total_w / 2   # frame column width
    row_h    = col_w / frame_ar   # height that preserves aspect ratio
    fig_h    = 5 * row_h + 2.0   # 5 rows + top margin for suptitle

    fig = plt.figure(figsize=(total_w, fig_h))
    fig.patch.set_facecolor('white')
    gs = fig.add_gridspec(
        5, 2,
        width_ratios=[1, 1],
        hspace=0.40,    # generous vertical gap to avoid label overlap
        wspace=0.08,
    )
    fig.suptitle(
        "Representative frames per quality class — Bandeja dataset (484 clips, 6 players)\n"
        "Right column: joint Y displacements relative to the pelvis reference point",
        fontsize=12, fontweight='bold', y=1.01
    )

    for row, clip_info in enumerate(clips):
        ax_frame = fig.add_subplot(gs[row, 0])
        ax_traj  = fig.add_subplot(gs[row, 1])

        if clip_info is None:
            for ax in (ax_frame, ax_traj):
                ax.axis('off')
            continue

        label      = clip_info['label']
        color      = clip_info['color']
        grade      = clip_info['grade']
        player_id  = clip_info['player_id']
        clip_name  = clip_info['clip_name']
        json_path  = clip_info['json_path']
        video_path = clip_info['video_path']

        # ---- Column 0: video frame at natural aspect ratio ----
        ax_frame.axis('off')
        frame_ok = False
        if video_path and _cv2 is not None:
            try:
                frame = _extract_video_frame(video_path, pct=0.40)
                # Display at natural resolution — imshow default is aspect='equal'
                ax_frame.imshow(frame)
                frame_ok = True
            except Exception as e:
                print(f"  [WARN] {label} frame: {e}")

        if not frame_ok:
            ax_frame.set_facecolor('#eeeeee')
            ax_frame.text(0.5, 0.5, 'Frame unavailable', ha='center', va='center',
                          transform=ax_frame.transAxes, fontsize=9, color='#888888')

        # Color-coded quality badge as axis title
        ax_frame.set_title(
            label, fontsize=12, fontweight='bold', color='white', pad=5,
            bbox=dict(boxstyle='round,pad=0.35', facecolor=color,
                      edgecolor='none', alpha=0.93)
        )
        # Clip metadata as a semi-transparent label inside the image (bottom-left)
        ax_frame.annotate(
            f"Player {player_id}  ·  Grade {grade}\n{clip_name}",
            xy=(0.01, 0.02), xycoords='axes fraction',
            fontsize=7.5, color='white', va='bottom',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='black', alpha=0.55,
                      edgecolor='none')
        )

        # ---- Column 1: trajectory subplot ----
        try:
            coords       = load_coordinates(json_path)
            wrist_ref    = coords['wrist_ref']
            elbow_ref    = coords['elbow_ref']
            shoulder_ref = coords['shoulder_ref']
            n  = len(wrist_ref)
            fr = np.arange(n)

            ax_traj.plot(fr, wrist_ref[:, 1],  color='#d62728', lw=1.5,
                         label='Right Wrist Y')
            ax_traj.plot(fr, elbow_ref[:, 1],  color='#1f77b4', lw=1.5,
                         label='Right Elbow Y')
            if shoulder_ref is not None:
                ax_traj.plot(fr, shoulder_ref[:, 1], color='#2ca02c', lw=1.5,
                             label='Left Shoulder Y')

            ax_traj.set_xlabel('Frame number', fontsize=9)
            ax_traj.set_ylabel('Y displacement from pelvis (px)', fontsize=9)
            ax_traj.set_title(
                f'{label} — vertical joint displacements\n'
                '(relative to pelvis reference point)',
                fontsize=9.5, fontweight='bold'
            )
            ax_traj.legend(fontsize=8.5, loc='upper right')
            ax_traj.grid(True, alpha=0.3)
            ax_traj.set_facecolor('#fafafa')
            ax_traj.tick_params(labelsize=8)
            ax_traj.set_xlim(0, max(n - 1, 1))

        except Exception as e:
            ax_traj.axis('off')
            ax_traj.text(0.5, 0.5, f'Trajectory unavailable\n{e}',
                         ha='center', va='center', transform=ax_traj.transAxes,
                         fontsize=7, color='#888888')

    out_path = os.path.join(out_dir, 'dataset_mosaic.png')
    plt.savefig(out_path, dpi=config.PLOT_DPI, bbox_inches='tight', facecolor='white')
    plt.close()
    print(f"[OK] dataset_mosaic.png -> {out_path}")


def thesis_trajectories(args: argparse.Namespace) -> None:
    """Generate all labeled trajectory figures for the thesis Methodology chapter.

    Auto-selects one representative clip for Very Low (class 0), Medium (class 2),
    and Excellent (class 4) from coords_dir.  For each clip it produces:

    - trajectory_temporal_{clip_name}.png  — X/Y over frame for wrist, elbow, shoulder
    - trajectory_3d_{clip_name}.png        — 3D trajectory (X, Y, Frame axis)

    For the Very Low / Excellent pair it also produces:
    - trajectory_wrist_comparison_{vl}_vs_{exc}.png  — normalised wrist-Y overlay

    For the Excellent clip only:
    - joint_trajectories_{clip_name}.png   — 2×2 panel: pelvis, shoulder, elbow, wrist

    All figure titles include the full clip filename so images can be identified
    unambiguously when placed in the thesis document.

    Output directory: {thesis_dir}/Images/Methodology/

    CLI usage:
        python main.py thesisTrajectories --coords_dir "../Coordinates" \\
               [--thesis_dir "..."]
    """
    matplotlib.use('Agg')

    coords_dir = args.coords_dir
    thesis_dir = config.get_thesis_dir(args)
    out_dir    = os.path.join(thesis_dir, 'Images', 'Methodology')
    os.makedirs(out_dir, exist_ok=True)

    # ---- Auto-select one clip per target class ----
    target = {0: None, 2: None, 4: None}
    for root, _, files in os.walk(coords_dir):
        for fname in sorted(files):
            if not fname.endswith('.json'):
                continue
            meta = _parse_clip_meta(fname)
            if meta is None:
                continue
            _, _, _, grade = meta
            cls = config.grade_to_class(grade)
            if cls in target and target[cls] is None:
                target[cls] = os.path.join(root, fname)
        if all(v is not None for v in target.values()):
            break

    label_map = {0: 'Very Low', 2: 'Medium', 4: 'Excellent'}

    generated = []

    for cls, json_path in target.items():
        if json_path is None:
            print(f"[WARN] No clip found for class {label_map[cls]}")
            continue

        clip_name = os.path.splitext(os.path.basename(json_path))[0]
        label     = label_map[cls]
        print(f"\n[INFO] {label} clip: {clip_name}")
        coords = load_coordinates(json_path)

        # Temporal plot
        t_out = os.path.join(out_dir, f'trajectory_temporal_{clip_name}.png')
        _save_temporal_plot(
            coords,
            title=f'Joint Trajectories over Frame — {label} Execution',
            clip_name=clip_name,
            out_path=t_out
        )
        generated.append(t_out)
        print(f"  [OK] trajectory_temporal_{clip_name}.png")

        # 3D plot
        d3_out = os.path.join(out_dir, f'trajectory_3d_{clip_name}.png')
        _save_3d_plot_file(
            coords,
            title=f'3D Trajectories (X, Y, Frame) — {label} Execution',
            clip_name=clip_name,
            out_path=d3_out
        )
        generated.append(d3_out)
        print(f"  [OK] trajectory_3d_{clip_name}.png")

    # ---- Wrist-Y comparison: Very Low vs Excellent ----
    if target[0] and target[4]:
        vl_name  = os.path.splitext(os.path.basename(target[0]))[0]
        exc_name = os.path.splitext(os.path.basename(target[4]))[0]
        c_vl     = load_coordinates(target[0])
        c_exc    = load_coordinates(target[4])

        def _norm01(arr):
            mn, mx = arr.min(), arr.max()
            return (arr - mn) / (mx - mn + 1e-8)

        w_vl  = _norm01(c_vl['wrist_ref'][:, 1].astype(float))
        w_exc = _norm01(c_exc['wrist_ref'][:, 1].astype(float))

        fig, ax = plt.subplots(figsize=(11, 5))
        fig.patch.set_facecolor('white')
        ax.plot(np.arange(len(w_vl)),  w_vl,  color='#d62728', lw=2.0,
                label=f'Very Low — {vl_name}')
        ax.plot(np.arange(len(w_exc)), w_exc, color='#9467bd', lw=2.0,
                label=f'Excellent — {exc_name}')
        ax.set_xlabel('Frame number', fontsize=11)
        ax.set_ylabel('Wrist Y displacement from pelvis (normalized 0–1)', fontsize=10)
        ax.set_title(
            'Right-Wrist Vertical Trajectory: Very Low vs Excellent Execution\n'
            f'{vl_name}  vs  {exc_name}',
            fontsize=11, fontweight='bold'
        )
        ax.legend(fontsize=10)
        ax.set_facecolor('#fafafa')
        ax.grid(True, alpha=0.3)
        ax.text(0.02, 0.97,
                "Wrist Y = vertical displacement from pelvis (px), normalized to [0, 1]\n"
                "for each clip independently to compare movement patterns across quality levels.",
                transform=ax.transAxes, fontsize=8, va='top', color='#555555',
                style='italic',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='#f5f5f5',
                          edgecolor='#cccccc', alpha=0.9))

        cmp_out = os.path.join(out_dir,
                               f'trajectory_wrist_comparison_{vl_name}_vs_{exc_name}.png')
        plt.tight_layout()
        plt.savefig(cmp_out, dpi=config.PLOT_DPI, bbox_inches='tight', facecolor='white')
        plt.close()
        generated.append(cmp_out)
        print(f"\n[OK] {os.path.basename(cmp_out)}")

    # ---- Per-joint 4-panel for Excellent clip ----
    if target[4]:
        exc_name = os.path.splitext(os.path.basename(target[4]))[0]
        coords   = load_coordinates(target[4])

        pelvis       = coords['pelvis']
        shoulder_ref = coords['shoulder_ref']
        elbow_ref    = coords['elbow_ref']
        wrist_ref    = coords['wrist_ref']
        n      = len(pelvis)
        frames = np.arange(n)

        # Pelvis = absolute pixel coordinates. All others = displacement from pelvis.
        panels = [
            ('Pelvis',
             'Absolute pixel position in frame (px)',
             pelvis),
            ('Left Shoulder\n(relative to pelvis)',
             'Displacement from pelvis (px)',
             shoulder_ref if shoulder_ref is not None else np.zeros((n, 2))),
            ('Right Elbow\n(relative to pelvis)',
             'Displacement from pelvis (px)',
             elbow_ref),
            ('Right Wrist\n(relative to pelvis)',
             'Displacement from pelvis (px)',
             wrist_ref),
        ]

        fig, axes = plt.subplots(2, 2, figsize=(14, 8))
        fig.patch.set_facecolor('white')
        fig.suptitle(
            f'Per-Joint X/Y Trajectories over Frames — Excellent Execution\nClip: {exc_name}\n'
            'Pelvis: absolute pixel coordinates  |  Other joints: displacement from pelvis',
            fontsize=11, fontweight='bold'
        )

        for ax, (jname, ylabel, jdata) in zip(axes.flat, panels):
            ax.plot(frames, jdata[:n, 0], color='steelblue',  lw=1.8, label='x (horizontal)')
            ax.plot(frames, jdata[:n, 1], color='darkorange', lw=1.8, label='y (vertical)')
            ax.set_title(jname, fontsize=11, fontweight='bold')
            ax.set_xlabel('Frame number (0–89)', fontsize=9)
            ax.set_ylabel(ylabel, fontsize=9)
            ax.legend(fontsize=9)
            ax.set_facecolor('#fafafa')
            ax.grid(True, alpha=0.3)
            ax.set_xlim(0, max(n - 1, 89))

        pj_out = os.path.join(out_dir, f'joint_trajectories_{exc_name}.png')
        plt.tight_layout()
        plt.savefig(pj_out, dpi=config.PLOT_DPI, bbox_inches='tight', facecolor='white')
        plt.close()
        generated.append(pj_out)
        print(f"[OK] joint_trajectories_{exc_name}.png")

    print(f"\n[SUMMARY] {len(generated)} files saved to {out_dir}")


def save_animation_gif(args: argparse.Namespace) -> None:
    """Save the motion animation for one clip as an animated GIF.

    Renders the same kinematic-chain animation as the interactive `animate`
    command but writes the result to disk using Pillow (no display required).
    Playback speed is controlled by config.ANIMATION_PLAYBACK_SPEED.

    Output: {out_dir}/{clip_name}_animation.gif
        Default out_dir: {thesis_dir}/Images/Methodology/

    CLI usage:
        python main.py saveAnimation --file "../Coordinates/player10/..."
               [--out_dir "path/to/output"] [--thesis_dir "..."]
    """
    matplotlib.use('Agg')

    json_path = args.file
    out_dir   = (getattr(args, 'out_dir', None)
                 or os.path.join(config.get_thesis_dir(args), 'Images', 'Methodology'))
    os.makedirs(out_dir, exist_ok=True)

    clip_name = os.path.splitext(os.path.basename(json_path))[0]
    print(f"[INFO] Generating animation GIF for: {clip_name}")

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    pelvis     = np.array(data[config.FIELD_PELVIS])
    elbow      = np.array(data[config.FIELD_ELBOW_ORIGINAL])
    wrist      = np.array(data[config.FIELD_WRIST_ORIGINAL])
    timestamps = np.array(data['timestamps'])
    meta       = data.get('metadata', {})
    fps        = float(meta.get('fps', 30))

    has_shoulder = (config.FIELD_SHOULDER_ORIGINAL in data
                    and len(data[config.FIELD_SHOULDER_ORIGINAL]) > 0)
    shoulder = np.array(data[config.FIELD_SHOULDER_ORIGINAL]) if has_shoulder else None

    all_pts = np.vstack([pelvis, elbow, wrist] + ([shoulder] if has_shoulder else []))
    x_min, x_max = all_pts[:, 0].min(), all_pts[:, 0].max()
    y_min, y_max = all_pts[:, 1].min(), all_pts[:, 1].max()
    mx = (x_max - x_min) * config.COORDINATE_MARGIN_RATIO
    my = (y_max - y_min) * config.COORDINATE_MARGIN_RATIO

    fig, ax = plt.subplots(figsize=(7, 7))
    fig.patch.set_facecolor('white')
    ax.set_facecolor('#fafafa')
    ax.set_title(f'Motion Animation\n{clip_name}', fontsize=10)
    ax.set_xlim(x_min - mx, x_max + mx)
    ax.set_ylim(y_min - my, y_max + my)
    ax.set_xlabel('X (px)')
    ax.set_ylabel('Y (px)')
    ax.grid(True, linestyle='--', alpha=0.4)

    scat_pelvis, = ax.plot([], [], 'o', color='blue',   label='Pelvis',      markersize=8)
    scat_elbow,  = ax.plot([], [], 'o', color='green',  label='Right Elbow', markersize=8)
    scat_wrist,  = ax.plot([], [], 'o', color='red',    label='Right Wrist', markersize=8)
    line_arm,    = ax.plot([], [], '-', color='orange',  lw=2, label='Arm')
    trail_p,     = ax.plot([], [], '--', color='blue',   alpha=0.35)
    trail_e,     = ax.plot([], [], '--', color='green',  alpha=0.35)
    trail_w,     = ax.plot([], [], '--', color='red',    alpha=0.35)

    artists = [scat_pelvis, scat_elbow, scat_wrist, line_arm, trail_p, trail_e, trail_w]

    if has_shoulder:
        scat_sh,  = ax.plot([], [], 'o',  color='purple', label='Left Shoulder', markersize=8)
        trail_sh, = ax.plot([], [], '--', color='purple',  alpha=0.35)
        artists.extend([scat_sh, trail_sh])

    ax.legend(loc='upper left', fontsize=7)

    def _init():
        for a in artists:
            a.set_data([], [])
        return tuple(artists)

    def _update(i):
        px, py = pelvis[i]
        ex, ey = elbow[i]
        wx, wy = wrist[i]
        scat_pelvis.set_data([px], [py])
        scat_elbow.set_data([ex], [ey])
        scat_wrist.set_data([wx], [wy])
        trail_p.set_data(pelvis[:i, 0], pelvis[:i, 1])
        trail_e.set_data(elbow[:i, 0],  elbow[:i, 1])
        trail_w.set_data(wrist[:i, 0],  wrist[:i, 1])
        if has_shoulder:
            sx, sy = shoulder[i]
            scat_sh.set_data([sx], [sy])
            trail_sh.set_data(shoulder[:i, 0], shoulder[:i, 1])
            line_arm.set_data([px, sx, ex, wx], [py, sy, ey, wy])
        else:
            line_arm.set_data([ex, wx], [ey, wy])
        return tuple(artists)

    interval = int(1000 / (fps * config.ANIMATION_PLAYBACK_SPEED))
    ani = animation.FuncAnimation(
        fig, _update, frames=len(timestamps),
        init_func=_init, blit=True, interval=interval, repeat=False
    )

    out_path = os.path.join(out_dir, f'{clip_name}_animation.gif')
    try:
        writer = animation.PillowWriter(
            fps=max(1, int(fps * config.ANIMATION_PLAYBACK_SPEED))
        )
        ani.save(out_path, writer=writer)
        print(f"[OK] Animation GIF -> {out_path}")
    except Exception as e:
        print(f"[ERROR] Could not save GIF: {e}")
        print("       Ensure Pillow is installed: pip install Pillow")
    finally:
        plt.close()
