"""
module_grapher.py
=================
Data visualization and animation module for coordinate data.

Provides functions to plot original coordinates, pelvis-relative coordinates,
temporal evolution, 3D trajectories, and animated motion sequences from
the JSON coordinate files generated by the pose estimation pipeline.

Supports 4 keypoints: Pelvis, Right Shoulder, Right Elbow, Right Wrist.
Backward-compatible with older 3-keypoint JSONs (without shoulder data).

Author: Cesar Emilio Castaño Marin
"""

import json
import os
import argparse
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import cm
import matplotlib.animation as animation
import seaborn as sns
from typing import Tuple, Optional
from collections import Counter
from sklearn.metrics import confusion_matrix, accuracy_score

import config


# ===========================
#  MODULE 1: Load Data
# ===========================
def load_coordinates(file_path: str) -> dict:
    """Load coordinates and timestamps from JSON file.

    Returns a dict with keys: pelvis, shoulder, shoulder_ref, wrist, wrist_ref,
    elbow, elbow_ref, timestamps. Shoulder fields may be None if not present
    in the JSON (backward compatibility with 3-keypoint data).

    Raises
    ------
    FileNotFoundError
        If the file does not exist.
    json.JSONDecodeError
        If the file contains invalid JSON.
    KeyError
        If required coordinate fields are missing from the JSON.
    """
    if not os.path.isfile(file_path):
        raise FileNotFoundError(f"File not found: {file_path}")

    with open(file_path, "r") as file:
        data = json.load(file)

    required_keys = [config.FIELD_PELVIS, config.FIELD_WRIST_ORIGINAL,
                     config.FIELD_WRIST_RELATIVE, config.FIELD_ELBOW_ORIGINAL,
                     config.FIELD_ELBOW_RELATIVE, "timestamps"]
    for key in required_keys:
        if key not in data:
            raise KeyError(f"Missing required key '{key}' in {file_path}")

    result = {
        "pelvis": np.array(data[config.FIELD_PELVIS]),
        "wrist": np.array(data[config.FIELD_WRIST_ORIGINAL]),
        "wrist_ref": np.array(data[config.FIELD_WRIST_RELATIVE]),
        "elbow": np.array(data[config.FIELD_ELBOW_ORIGINAL]),
        "elbow_ref": np.array(data[config.FIELD_ELBOW_RELATIVE]),
        "timestamps": np.array(data["timestamps"]),
        "shoulder": None,
        "shoulder_ref": None,
    }

    if config.FIELD_SHOULDER_ORIGINAL in data and len(data[config.FIELD_SHOULDER_ORIGINAL]) > 0:
        result["shoulder"] = np.array(data[config.FIELD_SHOULDER_ORIGINAL])
        result["shoulder_ref"] = np.array(data[config.FIELD_SHOULDER_RELATIVE])

    return result

# ===========================
#  MODULE 2: Plot Functions
# ===========================

def plot_original_coordinates(pelvis: np.ndarray, wrist: np.ndarray, elbow: np.ndarray,
                              shoulder: Optional[np.ndarray] = None) -> None:
    """Plot original (absolute) coordinates of all keypoints."""
    num_points = len(pelvis)

    colors_pelvis = cm.Blues(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))
    colors_wrist = cm.Reds(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))
    colors_elbow = cm.Purples(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))
    colors_shoulder = cm.Greens(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))

    has_shoulder = shoulder is not None
    n_cols = 3 if has_shoulder else 2
    fig, axs = plt.subplots(1, n_cols, figsize=(6 * n_cols, 6))

    # ========== SUBPLOT A: Pelvis + Wrist ==========
    axs[0].set_title("Original Coordinates: Pelvis & Wrist")
    for i in range(num_points - 1):
        axs[0].plot([pelvis[i, 0], pelvis[i+1, 0]],
                    [pelvis[i, 1], pelvis[i+1, 1]], color=colors_pelvis[i])
        axs[0].plot([wrist[i, 0], wrist[i+1, 0]],
                    [wrist[i, 1], wrist[i+1, 1]], color=colors_wrist[i])

    axs[0].scatter(pelvis[:, 0], pelvis[:, 1], c=colors_pelvis, s=20, label="Pelvis")
    axs[0].scatter(wrist[:, 0], wrist[:, 1], c=colors_wrist, s=20, label="Wrist")
    axs[0].set_aspect("equal")
    axs[0].legend()
    axs[0].set_xlabel("Distance (px)")
    axs[0].set_ylabel("Distance (px)")

    # ========== SUBPLOT B: Pelvis + Elbow ==========
    axs[1].set_title("Original Coordinates: Pelvis & Elbow")
    for i in range(num_points - 1):
        axs[1].plot([pelvis[i, 0], pelvis[i+1, 0]],
                    [pelvis[i, 1], pelvis[i+1, 1]], color=colors_pelvis[i])
        axs[1].plot([elbow[i, 0], elbow[i+1, 0]],
                    [elbow[i, 1], elbow[i+1, 1]], color=colors_elbow[i])

    axs[1].scatter(pelvis[:, 0], pelvis[:, 1], c=colors_pelvis, s=20, label="Pelvis")
    axs[1].scatter(elbow[:, 0], elbow[:, 1], c=colors_elbow, s=20, label="Elbow")
    axs[1].set_aspect("equal")
    axs[1].legend()
    axs[1].set_xlabel("Distance (px)")
    axs[1].set_ylabel("Distance (px)")

    # ========== SUBPLOT C: Pelvis + Shoulder (if available) ==========
    if has_shoulder:
        axs[2].set_title("Original Coordinates: Pelvis & Shoulder")
        for i in range(num_points - 1):
            axs[2].plot([pelvis[i, 0], pelvis[i+1, 0]],
                        [pelvis[i, 1], pelvis[i+1, 1]], color=colors_pelvis[i])
            axs[2].plot([shoulder[i, 0], shoulder[i+1, 0]],
                        [shoulder[i, 1], shoulder[i+1, 1]], color=colors_shoulder[i])

        axs[2].scatter(pelvis[:, 0], pelvis[:, 1], c=colors_pelvis, s=20, label="Pelvis")
        axs[2].scatter(shoulder[:, 0], shoulder[:, 1], c=colors_shoulder, s=20, label="Shoulder")
        axs[2].set_aspect("equal")
        axs[2].legend()
        axs[2].set_xlabel("Distance (px)")
        axs[2].set_ylabel("Distance (px)")

    fig.text(
        0.5, 0.02,
        "Lighter colors represent the beginning of the movement, while darker colors indicate its end.",
        ha="center", fontsize=9, style="italic"
    )

    plt.tight_layout(rect=[0, 0.05, 1, 1])
    plt.show()

def plot_relative_coordinates(wrist_ref: np.ndarray, elbow_ref: np.ndarray,
                              shoulder_ref: Optional[np.ndarray] = None) -> None:
    """Plot pelvis-relative coordinates of wrist, elbow, and optionally shoulder."""
    num_points = len(wrist_ref)

    colors_wrist = cm.Greens(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))
    colors_elbow = cm.Oranges(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))
    colors_shoulder = cm.Blues(np.linspace(config.COLORMAP_RANGE_START, 1, num_points))

    has_shoulder = shoulder_ref is not None
    n_cols = 3 if has_shoulder else 2
    fig, axs = plt.subplots(1, n_cols, figsize=(6 * n_cols, 6))

    # ========== SUBPLOT A: Wrist relative ==========
    axs[0].set_title("Relative Coordinates: Wrist - Pelvis")
    for i in range(num_points - 1):
        axs[0].plot([wrist_ref[i, 0], wrist_ref[i+1, 0]],
                    [wrist_ref[i, 1], wrist_ref[i+1, 1]], color=colors_wrist[i])
    axs[0].scatter(wrist_ref[:, 0], wrist_ref[:, 1], c=colors_wrist, s=20)
    axs[0].set_aspect("equal")
    axs[0].set_xlabel("Distance (px)")
    axs[0].set_ylabel("Distance (px)")

    # ========== SUBPLOT B: Elbow relative ==========
    axs[1].set_title("Relative Coordinates: Elbow - Pelvis")
    for i in range(num_points - 1):
        axs[1].plot([elbow_ref[i, 0], elbow_ref[i+1, 0]],
                    [elbow_ref[i, 1], elbow_ref[i+1, 1]], color=colors_elbow[i])
    axs[1].scatter(elbow_ref[:, 0], elbow_ref[:, 1], c=colors_elbow, s=20)
    axs[1].set_aspect("equal")
    axs[1].set_xlabel("Distance (px)")
    axs[1].set_ylabel("Distance (px)")

    # ========== SUBPLOT C: Shoulder relative (if available) ==========
    if has_shoulder:
        axs[2].set_title("Relative Coordinates: Shoulder - Pelvis")
        for i in range(num_points - 1):
            axs[2].plot([shoulder_ref[i, 0], shoulder_ref[i+1, 0]],
                        [shoulder_ref[i, 1], shoulder_ref[i+1, 1]], color=colors_shoulder[i])
        axs[2].scatter(shoulder_ref[:, 0], shoulder_ref[:, 1], c=colors_shoulder, s=20)
        axs[2].set_aspect("equal")
        axs[2].set_xlabel("Distance (px)")
        axs[2].set_ylabel("Distance (px)")

    fig.text(
        0.5, 0.02,
        "Lighter colors represent the beginning of the movement, while darker colors indicate its end.",
        ha="center", fontsize=9, style="italic"
    )

    plt.tight_layout(rect=[0, 0.05, 1, 1])
    plt.show()

def plot_temporal(wrist_ref: np.ndarray, elbow_ref: np.ndarray, timestamps: np.ndarray,
                  shoulder_ref: Optional[np.ndarray] = None) -> None:
    """Plot time progression for wrist, elbow, and optionally shoulder (X & Y)."""

    has_shoulder = shoulder_ref is not None
    n_rows = 3 if has_shoulder else 2
    fig, axs = plt.subplots(n_rows, 2, figsize=(12, 5 * n_rows), sharex=True)

    # ------------------------
    # Row 0: Wrist X / Y
    # ------------------------
    axs[0, 0].set_title("Wrist X over Time")
    axs[0, 0].plot(timestamps, wrist_ref[:, 0], color="green")
    axs[0, 0].grid(True)
    axs[0, 0].set_xlabel("Time (seconds)")
    axs[0, 0].set_ylabel("Distance to Reference (px)")

    axs[0, 1].set_title("Wrist Y over Time")
    axs[0, 1].plot(timestamps, wrist_ref[:, 1], color="darkgreen")
    axs[0, 1].grid(True)
    axs[0, 1].set_xlabel("Time (seconds)")
    axs[0, 1].set_ylabel("Distance to Reference (px)")

    # ------------------------
    # Row 1: Elbow X / Y
    # ------------------------
    axs[1, 0].set_title("Elbow X over Time")
    axs[1, 0].plot(timestamps, elbow_ref[:, 0], color="orange")
    axs[1, 0].grid(True)
    axs[1, 0].set_xlabel("Time (seconds)")
    axs[1, 0].set_ylabel("Distance to Reference (px)")

    axs[1, 1].set_title("Elbow Y over Time")
    axs[1, 1].plot(timestamps, elbow_ref[:, 1], color="red")
    axs[1, 1].grid(True)
    axs[1, 1].set_xlabel("Time (seconds)")
    axs[1, 1].set_ylabel("Distance to Reference (px)")

    # ------------------------
    # Row 2: Shoulder X / Y (if available)
    # ------------------------
    if has_shoulder:
        axs[2, 0].set_title("Shoulder X over Time")
        axs[2, 0].plot(timestamps, shoulder_ref[:, 0], color="blue")
        axs[2, 0].grid(True)
        axs[2, 0].set_xlabel("Time (seconds)")
        axs[2, 0].set_ylabel("Distance to Reference (px)")

        axs[2, 1].set_title("Shoulder Y over Time")
        axs[2, 1].plot(timestamps, shoulder_ref[:, 1], color="darkblue")
        axs[2, 1].grid(True)
        axs[2, 1].set_xlabel("Time (seconds)")
        axs[2, 1].set_ylabel("Distance to Reference (px)")

    plt.tight_layout()
    plt.show()

def plot_3d(wrist_ref: np.ndarray, elbow_ref: np.ndarray, timestamps: np.ndarray,
            shoulder_ref: Optional[np.ndarray] = None) -> None:
    """3D trajectory of wrist, elbow, and optionally shoulder (X, Y, Time)."""

    has_shoulder = shoulder_ref is not None
    n_cols = 3 if has_shoulder else 2
    fig = plt.figure(figsize=(7 * n_cols, 6))

    # ===== Wrist =====
    ax1 = fig.add_subplot(1, n_cols, 1, projection="3d")
    ax1.plot3D(wrist_ref[:, 0], timestamps, wrist_ref[:, 1], color="green")
    ax1.set_title("3D Wrist Trajectory (X, Y, Time)")
    ax1.set_xlabel("Distance in X to Reference (px)")
    ax1.set_ylabel("Time")
    ax1.set_zlabel("Distance in Y to Reference (px)")

    # ===== Elbow =====
    ax2 = fig.add_subplot(1, n_cols, 2, projection="3d")
    ax2.plot3D(elbow_ref[:, 0], timestamps, elbow_ref[:, 1], color="purple")
    ax2.set_title("3D Elbow Trajectory (X, Y, Time)")
    ax2.set_xlabel("Distance in X to Reference (px)")
    ax2.set_ylabel("Time")
    ax2.set_zlabel("Distance in Y to Reference (px)")

    # ===== Shoulder =====
    if has_shoulder:
        ax3 = fig.add_subplot(1, n_cols, 3, projection="3d")
        ax3.plot3D(shoulder_ref[:, 0], timestamps, shoulder_ref[:, 1], color="blue")
        ax3.set_title("3D Shoulder Trajectory (X, Y, Time)")
        ax3.set_xlabel("Distance in X to Reference (px)")
        ax3.set_ylabel("Time")
        ax3.set_zlabel("Distance in Y to Reference (px)")

    plt.tight_layout()
    plt.show()

# ===========================
#  MODULE 3: Parser Wrapper
# ===========================
def plot_coordinates(args: argparse.Namespace) -> None:
    """Main function that receives parser arguments and calls the appropriate plot."""
    coords = load_coordinates(args.file)

    pelvis = coords["pelvis"]
    wrist = coords["wrist"]
    wrist_ref = coords["wrist_ref"]
    elbow = coords["elbow"]
    elbow_ref = coords["elbow_ref"]
    timestamps = coords["timestamps"]
    shoulder = coords["shoulder"]
    shoulder_ref = coords["shoulder_ref"]

    print(f"\n[INFO] File loaded: {args.file}")
    print(f"[INFO] Plot type selected: {args.type}")
    if shoulder is not None:
        print("[INFO] Shoulder data found (4-keypoint format)\n")
    else:
        print("[INFO] No shoulder data (3-keypoint format)\n")

    if args.type == "original":
        plot_original_coordinates(pelvis, wrist, elbow, shoulder)

    elif args.type == "relative":
        plot_relative_coordinates(wrist_ref, elbow_ref, shoulder_ref)

    elif args.type == "temporal":
        plot_temporal(wrist_ref, elbow_ref, timestamps, shoulder_ref)

    elif args.type == "3d":
        plot_3d(wrist_ref, elbow_ref, timestamps, shoulder_ref)

    elif args.type == "all":
        plot_original_coordinates(pelvis, wrist, elbow, shoulder)
        plot_relative_coordinates(wrist_ref, elbow_ref, shoulder_ref)
        plot_temporal(wrist_ref, elbow_ref, timestamps, shoulder_ref)
        plot_3d(wrist_ref, elbow_ref, timestamps, shoulder_ref)

# ===========================
#  MODULE 4: Motion Animation
# ===========================
def animate_motion(args: argparse.Namespace) -> None:
    """
    Animates Pelvis, Left Shoulder, Right Elbow, and Right Wrist (original coordinates)
    with automatic zoom, normal Y-axis, and start markers for each joint.
    Connects joints as a kinematic chain: Pelvis -> Shoulder -> Elbow -> Wrist.
    """
    json_path = args.file
    print(f"\n[INFO] Generating animation from: {json_path}\n")

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    pelvis = np.array(data[config.FIELD_PELVIS])
    elbow = np.array(data[config.FIELD_ELBOW_ORIGINAL])
    wrist = np.array(data[config.FIELD_WRIST_ORIGINAL])
    timestamps = np.array(data["timestamps"])
    metadata = data.get("metadata", {})
    fps = metadata.get("fps", 30)

    has_shoulder = config.FIELD_SHOULDER_ORIGINAL in data and len(data[config.FIELD_SHOULDER_ORIGINAL]) > 0
    if has_shoulder:
        shoulder = np.array(data[config.FIELD_SHOULDER_ORIGINAL])

    # --- Playback speed (slower for clarity) ---
    playback_speed = config.ANIMATION_PLAYBACK_SPEED
    interval = (1000 / fps) / playback_speed

    # --- Compute coordinate bounds for zoom ---
    points_list = [pelvis, elbow, wrist]
    if has_shoulder:
        points_list.append(shoulder)
    all_points = np.vstack(points_list)
    x_min, x_max = np.min(all_points[:, 0]), np.max(all_points[:, 0])
    y_min, y_max = np.min(all_points[:, 1]), np.max(all_points[:, 1])
    margin_x = (x_max - x_min) * config.COORDINATE_MARGIN_RATIO
    margin_y = (y_max - y_min) * config.COORDINATE_MARGIN_RATIO

    # --- Setup figure ---
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_title(f"Motion Animation (Original) - Frontal View of the Player\n{metadata.get('video_name', '')}")
    ax.set_xlim(x_min - margin_x, x_max + margin_x)
    ax.set_ylim(y_min - margin_y, y_max + margin_y)
    ax.set_xlabel("Distance (px)")
    ax.set_ylabel("Distance (px)")
    ax.grid(True, linestyle="--", alpha=0.5)

    # --- Define graphical elements ---
    scat_pelvis, = ax.plot([], [], 'o', color='blue', label="Pelvis", markersize=8)
    scat_elbow, = ax.plot([], [], 'o', color='green', label="Right Elbow", markersize=8)
    scat_wrist, = ax.plot([], [], 'o', color='red', label="Right Wrist", markersize=8)

    # Kinematic chain line: pelvis -> (shoulder) -> elbow -> wrist
    line_arm, = ax.plot([], [], '-', color='orange', lw=2, label="Arm")

    # Trails
    trail_pelvis, = ax.plot([], [], '--', color='blue', alpha=0.4)
    trail_elbow, = ax.plot([], [], '--', color='green', alpha=0.4)
    trail_wrist, = ax.plot([], [], '--', color='red', alpha=0.4)

    # Start markers (hollow circles)
    start_pelvis, = ax.plot([], [], 'o', color='blue', markersize=10, fillstyle='none', label="Start Pelvis")
    start_elbow, = ax.plot([], [], 'o', color='green', markersize=10, fillstyle='none', label="Start Elbow")
    start_wrist, = ax.plot([], [], 'o', color='red', markersize=10, fillstyle='none', label="Start Wrist")

    # Shoulder-specific elements (only if data exists)
    all_elements = [scat_pelvis, scat_elbow, scat_wrist, line_arm,
                    trail_pelvis, trail_elbow, trail_wrist,
                    start_pelvis, start_elbow, start_wrist]

    if has_shoulder:
        scat_shoulder, = ax.plot([], [], 'o', color='purple', label="Left Shoulder", markersize=8)
        trail_shoulder, = ax.plot([], [], '--', color='purple', alpha=0.4)
        start_shoulder, = ax.plot([], [], 'o', color='purple', markersize=10, fillstyle='none', label="Start Shoulder")
        all_elements.extend([scat_shoulder, trail_shoulder, start_shoulder])

    ax.legend(loc='upper left', fontsize=7)

    # --- Initialization ---
    def init():
        for element in all_elements:
            element.set_data([], [])
        return tuple(all_elements)

    # --- Update function ---
    def update(i):
        px, py = pelvis[i]
        ex, ey = elbow[i]
        wx, wy = wrist[i]

        scat_pelvis.set_data(px, py)
        scat_elbow.set_data(ex, ey)
        scat_wrist.set_data(wx, wy)

        if has_shoulder:
            sx, sy = shoulder[i]
            scat_shoulder.set_data(sx, sy)
            # Kinematic chain: Pelvis -> Shoulder -> Elbow -> Wrist
            line_arm.set_data([px, sx, ex, wx], [py, sy, ey, wy])
            trail_shoulder.set_data(shoulder[:i, 0], shoulder[:i, 1])
            start_shoulder.set_data(shoulder[0, 0], shoulder[0, 1])
        else:
            # Without shoulder: Elbow -> Wrist only
            line_arm.set_data([ex, wx], [ey, wy])

        # Trails (motion history)
        trail_pelvis.set_data(pelvis[:i, 0], pelvis[:i, 1])
        trail_elbow.set_data(elbow[:i, 0], elbow[:i, 1])
        trail_wrist.set_data(wrist[:i, 0], wrist[:i, 1])

        # Start positions (fixed)
        start_pelvis.set_data(pelvis[0, 0], pelvis[0, 1])
        start_elbow.set_data(elbow[0, 0], elbow[0, 1])
        start_wrist.set_data(wrist[0, 0], wrist[0, 1])

        return tuple(all_elements)

    # --- Create animation ---
    ani = animation.FuncAnimation(
        fig, update, frames=len(timestamps),
        init_func=init, blit=True, interval=interval, repeat=False
    )

    plt.tight_layout()
    plt.show()


# ============================================================
#  THESIS ARTIFACT GENERATION
# ============================================================
# Private helpers for publication-ready figures.

def _plot_learning_curves(history: dict, display_name: str, out_path: str):
    """Plot and save learning curves (loss + accuracy) from training history."""
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 6))

    ax1.plot(history['loss'],     label='Training Loss')
    ax1.plot(history['val_loss'], label='Validation Loss')
    ax1.set_title(f'Learning Curves \u2014 {display_name}')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Loss')
    ax1.legend()
    ax1.grid(True)

    ax2.plot(history['accuracy'],     label='Training Accuracy')
    ax2.plot(history['val_accuracy'], label='Validation Accuracy')
    ax2.set_title(f'Learning Curves \u2014 {display_name}')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Accuracy')
    ax2.legend()
    ax2.grid(True)

    plt.tight_layout()
    plt.savefig(out_path, dpi=config.PLOT_DPI)
    plt.close()


def _plot_confusion_matrix(y_true, y_pred, display_name: str,
                           class_labels, out_path: str):
    """Plot and save a confusion matrix heatmap."""
    valid = sorted(set(list(y_true) + list(y_pred)))
    names = [class_labels[c] if c < len(class_labels) else str(c) for c in valid]
    cm_data = confusion_matrix(y_true, y_pred, labels=valid)

    plt.figure(figsize=(8, 6))
    sns.heatmap(cm_data, annot=True, fmt='d', cmap='Blues',
                xticklabels=names, yticklabels=names)
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title(f'Confusion Matrix \u2014 {display_name}')
    plt.tight_layout()
    plt.savefig(out_path, dpi=config.PLOT_DPI)
    plt.close()


def _plot_class_dist_thesis(y_true, y_pred, display_name: str,
                            class_labels, out_path: str):
    """Plot and save true vs predicted class distribution bar chart."""
    true_c = Counter(y_true)
    pred_c = Counter(y_pred)
    classes = sorted(set(list(true_c) + list(pred_c)))
    names = [class_labels[c] if c < len(class_labels) else str(c) for c in classes]

    plt.figure(figsize=(10, 6))
    x = np.arange(len(classes))
    plt.bar(x - 0.2, [true_c.get(c, 0) for c in classes], width=0.4, label='True')
    plt.bar(x + 0.2, [pred_c.get(c, 0) for c in classes], width=0.4, label='Predicted')
    plt.xticks(x, names, rotation=15)
    plt.title(f'True vs Predicted Class Distribution \u2014 {display_name}')
    plt.xlabel('Class')
    plt.ylabel('Clips')
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_path, dpi=config.PLOT_DPI)
    plt.close()


# -----------------------------------------------------------
# CLI-callable thesis functions
# -----------------------------------------------------------

def regen_plots(args: argparse.Namespace) -> None:
    """Regenerate all 15 experiment plots with English labels and display names.

    Reads learning curves from saved training_history.json and regenerates
    confusion matrix + class distribution by running inference on the test set
    reconstructed from the same random_state=42 split.

    Output: PNG files copied to the thesis Images/Experimentation/ directory.
    """
    from tf_keras.models import load_model as tf_load_model
    from Modules.module_data import load_all_jsons, build_test_set

    matplotlib.use('Agg')

    thesis_exp_dir = os.path.join(config.get_thesis_dir(args), 'Images', 'Experimentation')
    coords_dir = args.directory

    print(f"[INFO] Loading sequences from {coords_dir} ...")
    seqs, labels = load_all_jsons(coords_dir)
    print(f"[INFO] Loaded {len(seqs)} sequences")

    status = {}

    for exp in config.EXPERIMENTS:
        key          = exp['key']
        display_name = exp['display_name']
        results_dir  = os.path.join(config.RESULTS_DIR, exp['results_folder'])
        thesis_subdir = os.path.join(thesis_exp_dir, exp['thesis_subdir'])
        os.makedirs(thesis_subdir, exist_ok=True)

        exp_status = {'learning_curves': False, 'confusion_matrix': False,
                      'class_distribution': False}
        print(f"\n  [{key}] {display_name}")

        # ---- Learning curves ----
        hist_path = os.path.join(results_dir, 'training_history.json')
        if os.path.exists(hist_path):
            with open(hist_path) as f:
                history = json.load(f)
            _plot_learning_curves(
                history, display_name,
                os.path.join(thesis_subdir, 'learning_curves.png'))
            exp_status['learning_curves'] = True
            print(f"    [OK] learning_curves.png")
        else:
            print(f"    [SKIP] training_history.json not found")

        # ---- Confusion matrix + class distribution ----
        model_path = exp['model_path']
        if not os.path.exists(model_path):
            print(f"    [SKIP] model not found at {model_path}")
            status[key] = exp_status
            continue

        try:
            model      = tf_load_model(config.safe_model_path(model_path))
            n_features = model.input_shape[-1]
            n_out      = model.output_shape[-1]
            print(f"    [INFO] model loaded (inputs={n_features}, outputs={n_out})")

            X_test, y_test = build_test_set(seqs, labels, n_features)
            if X_test is None:
                print(f"    [SKIP] no matching test sequences for {n_features} features")
                status[key] = exp_status
                continue

            y_pred = np.argmax(model.predict(X_test, verbose=0), axis=1)
            if n_out != 5:
                y_pred = np.array([min(p // 2, 4) for p in y_pred])

            _plot_confusion_matrix(
                y_test, y_pred, display_name, config.CLASS_LABELS,
                os.path.join(thesis_subdir, 'confusion_matrix.png'))
            _plot_class_dist_thesis(
                y_test, y_pred, display_name, config.CLASS_LABELS,
                os.path.join(thesis_subdir, 'class_distribution.png'))

            exp_status['confusion_matrix']   = True
            exp_status['class_distribution'] = True
            print(f"    [OK] confusion_matrix.png + class_distribution.png "
                  f"(acc={accuracy_score(y_test, y_pred):.3f})")

        except Exception as err:
            print(f"    [ERROR] {err}")

        status[key] = exp_status

    # Summary
    print("\n[SUMMARY] Task regenPlots:")
    for key, s in status.items():
        parts = ' '.join(f"{k}={'OK' if v else 'FAIL'}" for k, v in s.items())
        print(f"  {key}: {parts}")


def label_dist(args: argparse.Namespace) -> None:
    """Generate dataset-wide class distribution histogram.

    Output: PNG saved to the thesis Images/Experimentation/ directory.
    """
    from Modules.module_data import load_all_jsons

    matplotlib.use('Agg')

    coords_dir = args.directory
    print(f"[INFO] Loading sequences from {coords_dir} ...")
    _, labels = load_all_jsons(coords_dir)
    print(f"[INFO] Loaded {len(labels)} labels")

    classes = [config.grade_to_class(g) for g in labels]
    counts  = [Counter(classes).get(c, 0) for c in range(5)]
    colors  = ['#2196F3', '#4CAF50', '#FF9800', '#F44336', '#9C27B0']

    plt.figure(figsize=(10, 6))
    bars = plt.bar(range(5), counts, color=colors)
    for bar, cnt in zip(bars, counts):
        plt.text(bar.get_x() + bar.get_width() / 2.0, bar.get_height() + 2,
                 str(cnt), ha='center', va='bottom', fontsize=11)
    plt.xticks(range(5), config.CLASS_LABELS)
    plt.xlabel('Quality Class')
    plt.ylabel('Number of Clips')
    plt.title(f'Class Distribution \u2014 Full Dataset ({len(labels)} clips)')
    plt.tight_layout()

    out_dir = os.path.join(config.get_thesis_dir(args), 'Images', 'Experimentation')
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, 'label_distribution.png')
    plt.savefig(out_path, dpi=config.PLOT_DPI)
    plt.close()

    print(f"[OK] label_distribution.png -> {out_path}")
    for c, cnt in zip(config.CLASS_LABELS, counts):
        print(f"  {c}: {cnt}")


def sys_output(args: argparse.Namespace) -> None:
    """Generate side-by-side low vs high quality joint trajectory figure.

    Scans all clips in *args.directory*, finds the first correctly classified
    Very Low/Low clip and first correctly classified Excellent clip using
    the BiLSTM Final Model (LSTM_Test03), and plots wrist and elbow Y
    trajectories side by side.

    Output: system_output_example.png saved to thesis Images/Methodology/.
    """
    from tf_keras.models import load_model as tf_load_model
    from tf_keras.utils import pad_sequences as kpad
    from Modules.module_data import normalize_sequence

    matplotlib.use('Agg')

    lstm_exp = next(e for e in config.EXPERIMENTS if e['key'] == 'LSTM_Test03')
    model_path = lstm_exp['model_path']
    if not os.path.exists(model_path):
        print(f"[SKIP] LSTM_Test03 model not found at {model_path}")
        return

    model = tf_load_model(config.safe_model_path(model_path))
    coords_dir = args.directory

    low_clip  = None   # class 0 or 1
    high_clip = None   # class 4

    for root, _, files in os.walk(coords_dir):
        for fname in files:
            if not fname.endswith('.json'):
                continue
            if low_clip and high_clip:
                break

            with open(os.path.join(root, fname)) as f:
                data = json.load(f)

            grade = int(data.get('metadata', {}).get('grade', 0) or 0)
            if grade == 0:
                continue

            true_class = config.grade_to_class(grade)
            if true_class not in [0, 1, 4]:
                continue
            if true_class in [0, 1] and low_clip:
                continue
            if true_class == 4 and high_clip:
                continue

            pelvis   = np.array(data.get(config.FIELD_PELVIS, []))
            shoulder = np.array(data.get(config.FIELD_SHOULDER_RELATIVE, []))
            elbow    = np.array(data.get(config.FIELD_ELBOW_RELATIVE, []))
            hand     = np.array(data.get(config.FIELD_WRIST_RELATIVE, []))

            if not (len(pelvis) and len(elbow) and len(hand)):
                continue

            if len(shoulder) > 0:
                L   = min(len(pelvis), len(shoulder), len(elbow), len(hand))
                seq = np.concatenate([pelvis[:L], shoulder[:L], elbow[:L], hand[:L]], axis=1)
            else:
                L   = min(len(pelvis), len(elbow), len(hand))
                seq = np.concatenate([pelvis[:L], elbow[:L], hand[:L]], axis=1)

            if L < 10 or seq.shape[1] != 8:
                continue

            norm_seq = normalize_sequence(seq)
            padded   = kpad([norm_seq], maxlen=config.MAX_SEQUENCE_LENGTH,
                            dtype='float32', padding='post', truncating='post')
            pred_class = int(np.argmax(model.predict(padded, verbose=0), axis=1)[0])

            if pred_class == true_class:
                clip = (seq, true_class, pred_class, fname)
                if true_class in [0, 1]:
                    low_clip  = clip
                else:
                    high_clip = clip

    if not low_clip or not high_clip:
        print(f"[WARN] Could not find both clip types "
              f"(low={'found' if low_clip else 'not found'}, "
              f"high={'found' if high_clip else 'not found'})")
        return

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    def _panel(ax, seq, pred_class, fname):
        n = min(len(seq), 90)
        ax.plot(np.arange(n), seq[:n, 7], label='Right Wrist Y',  linewidth=2)
        ax.plot(np.arange(n), seq[:n, 5], label='Right Elbow Y',  linewidth=2, linestyle='--')
        ax.set_xlabel('Frame')
        ax.set_ylabel('Relative Y Coordinate (px)')
        ax.legend()
        ax.grid(True, alpha=0.3)
        ax.text(0.05, 0.95,
                f'Predicted: {config.CLASS_LABELS[pred_class]}',
                transform=ax.transAxes, fontsize=12, verticalalignment='top',
                bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.8))

    low_seq, low_true, low_pred, low_file   = low_clip
    high_seq, high_true, high_pred, high_file = high_clip

    ax1.set_title(f'{config.CLASS_LABELS[low_true]} Quality Execution\n({low_file})')
    _panel(ax1, low_seq, low_pred, low_file)

    ax2.set_title(f'{config.CLASS_LABELS[high_true]} Quality Execution\n({high_file})')
    _panel(ax2, high_seq, high_pred, high_file)

    plt.suptitle('System Output Comparison \u2014 BiLSTM Final Model', fontsize=14)
    plt.tight_layout()

    out_dir = os.path.join(config.get_thesis_dir(args), 'Images', 'Methodology')
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, 'system_output_example.png')
    plt.savefig(out_path, dpi=config.PLOT_DPI)
    plt.close()
    print(f"[OK] system_output_example.png -> {out_path}")
